### PR TITLE
rare crash fix

### PR DESCRIPTION
**Pull request by lightX2**

### CODE REVIEW

**Comment by axxel** [comment]
Thanks for the PR. My understanding of the code is that the check you introduce here will always be evaluated as false. So before I merge that, I'd like understand how it can possibly be true. Can you provide an input image that triggers the crash you are fixing here?

**Comment by lightX2** [comment]
image

**Comment by axxel** [comment]
I don't see how the assertion failure you posted would be affected by the proposed change. This makes it even more important for me to get access to the input image data that triggered this. If you replace the `assert` line from your screenshot with
```
			if( !(line.points().empty() || p != line.points().back()) )
				throw 1;
```
And then replace your `ReadBardcode(...)` call with something along the lines of
```
	try {
		ReadBarcode(...);
	} catch ( int ) {
		// save the ImageView that was passed to a PNG file
	}
```

Then I can start investigating what is happening.

**Comment by lightX2** [comment]
send your email

**Comment by axxel** [comment]
I have not gotten any e-mail from you (I believe). Did you send me something?

**Comment by axxel** [comment]
Closing this now for the lack of feedback from the OP.

**Comment by jhay06** [comment]
this still recurring

**Comment by axxel** [comment]
I still need a sample image that allows me to reproduce the problem.

**Comment by lightX2** [comment]
i think something with not single image, but series.
later image processing is OK.
But we don't see problem for now in app

**Pull request closed without merging**
