### PR TITLE
c++20: add missing include

### PR DESCRIPTION
**Pull request by th1722**
Needed for std::movable.

### CODE REVIEW

**Comment by axxel** [comment]
Question: does this solve a compilation error on your setup?

The `#include` would need to move 3 lines up into the `#else` block to not (potentially) break the Android NDK support again.

**Comment by axxel** [comment]
The force-pushed changes you provided last week don't address my concern. Are you planing to modify the PR again?

**Comment by th1722** [comment]
> Question: does this solve a compilation error on your setup?
Yes, this solves "error: no type named 'movable' in namespace 'std'".

> The `#include` would need to move 3 lines up into the `#else` block to not (potentially) break the Android NDK support again.
> The force-pushed changes you provided last week don't address my concern. Are you planing to modify the PR again?

Fixed.

**Comment by th1722** [comment]
> Question: does this solve a compilation error on your setup?

Yes, this solves "error: no type named 'movable' in namespace 'std'".

> The `#include` would need to move 3 lines up into the `#else` block to not (potentially) break the Android NDK support again.

> The force-pushed changes you provided last week don't address my concern. Are you planing to modify the PR again?

Fixed.

**Comment by axxel** [comment]
Thanks.

**Pull request merged**
