### PR TITLE
Update Quadrilateral

### PR DESCRIPTION
**Pull request by MonkeybreadSoftware**
removed a and b being two variables.
a and b were used fro two different variables.

### CODE REVIEW

**Comment by axxel** [comment]
May I ask what the purpose / intent of this PR is?

**Comment by MonkeybreadSoftware** [comment]
Fixes a compiler warning about two variables a and b with same name and one shadows the other.

**Comment by axxel** [comment]
I see. I personally don't consider variable shadowing to be generally bad. Also the library compiles without any warnings in the default cmake config on my system. Did you explicitly enable that warning in yours? If not: what is your compiler/system you use? I assume this warning is showing up while compiling your client code?

**Comment by MonkeybreadSoftware** [comment]
Yes, we compile code with -Weverything using clang and then disable the warnings we don't like.
And if you include zxing in several files and build for multiple platforms, you see these warnings a lot of times.

**Comment by axxel** [comment]
Fair enough, I see your point. Is this the only annoying warning you get from including zxing-cpp?

**Comment by MonkeybreadSoftware** [comment]
Yes. That is the only warnings we saw. Otherwise it builds fine here.
I used to patch this myself and thought I would contribute this to make it permanent.

**Comment by axxel** [comment]
Thanks for your effort. As you can see, I chose a one-liner to achieve the same effect.

**Comment by MonkeybreadSoftware** [comment]
Thank you.

**Pull request closed without merging**
