### PR TITLE
feat: add read only for android analyser

### PR DESCRIPTION
**Pull request by adrienbusin**
Adding param closeImageAfterRead

 if true, image will be read and closed after analysis (Default, no regression).
 else this function will only read the image but it will not close image
  
This could be useful (it's my case) if you want to analyse image with other analyser in parallel and close image manually

### CODE REVIEW

**Comment by axxel** [comment]
Thanks for reaching out. I had a look at the code overall and the documentation of `ImageProxy` and came to the conclusion that what I was doing there (closing inside `read`) is just wrong from a conceptual point of view. Would you please update your PR to simply not close inside read and fix the demo-app to do that outside, just like for the Java path already.

This is a breaking change but the right thing to do in my opinion. Any comments from @markusfisch, @benjohnde?

**Comment by markusfisch** [comment]
Yes, I also think this is the right thing to do 👍 

(And another reason why I don't like having that `ImageProxy` dependency, but you know that already 😉)

**Comment by axxel** [comment]
I decided to make this 2-line commit myself instead of asking you to cleanup your PR. I hope you don't mind. Thanks for the collaboration.

**Comment by adrienbusin** [comment]
Ok ! thanks 🙂

**Pull request closed without merging**
