### PR TITLE
cmake: allow overriding python install directories

### PR DESCRIPTION
**Pull request by jameshilliard**
We may need to override these variables otherwise the python library may not get installed to the right location.

### CODE REVIEW

**Comment by axxel** [comment]
Question: why not simply use `cmake -DCMAKE_INSTALL_PREFIX=...` to direct your installation to where you want it?

**Comment by jameshilliard** [comment]
> Question: why not simply use `cmake -DCMAKE_INSTALL_PREFIX=...` to direct your installation to where you want it?

AFAIU using that would change the install location of the non-python targets which would not be desired.

**Comment by axxel** [comment]
> AFAIU using that would change the install location of the non-python targets which would not be desired.

That is correct. So are you actually installing not only the python module but also the c++-lib / example binaries? I'm curious: what is your use case? Packaging for some distribution?

**Comment by jameshilliard** [comment]
> So are you actually installing not only the python module but also the c++-lib / example binaries?

Yes.

> Packaging for some distribution?

For [buildroot](https://buildroot.org/).

**Pull request merged**
