### PR TITLE
Support "NW" style decode for OneD barcode

### PR DESCRIPTION
**Pull request by hellovigoss**
This pr provide a "NW" style reader for OneD barcode.
What N means Normail bar or space, and W means Wide bar or space.
NWCode style decode can be call like this
```c++
hints.setFormats(BarcodeFormat::NWCode);
hints.setTryDownscale(false).setTryInvert(false).setTryRotate(false).setTryHarder(false);
```

### CODE REVIEW

**Comment by axxel** [comment]
I had a glance at your code and it seems its purpose is to generate a text containing of the letters 'N' and 'W' depending on the width of the bars/spaces. Based on that I assume you are interested in debugging other 'real' codes?

**Comment by hellovigoss** [comment]
Our project need origin NW style made me do this thing.
I will be glad to debug 'real' code.

**Comment by axxel** [comment]
I don't know what you mean by "origin NW style". Can you provide a link to some specification or other technical description?

**Comment by hellovigoss** [comment]
ref: https://en.wikipedia.org/wiki/Interleaved_2_of_5

**Comment by axxel** [comment]
Interleaved 2 of 5 is already supported, see `BarcodeFormat::ITF`.

**Comment by hellovigoss** [comment]
got it! thx.

**Pull request closed without merging**
