### PR TITLE
Ignore .idea

### PR DESCRIPTION
**Pull request by okarmazin**
.idea should never be checked in. Applied globally to ensure it cannot creep in in any subproject.

This can be thought of as a completion of https://github.com/zxing-cpp/zxing-cpp/commit/52a5f2e7501ff9017536958a2056dec4a1a2dceb

### CODE REVIEW

**Comment by axxel** [comment]
Since this is already taken care of in the wrapper/android/.gitignore, I'd consider this issue solved. Are you using AndroidStudio anywhere "outside" of the wrapper/android directory?

**Comment by tiny-dancer** [comment]
I beleive .idea is a configuration file for all jetbrains ide's, including clion

**Comment by benjohnde** [comment]
Depends a bit on the usage though, won't do any harm.

**Comment by axxel** [comment]
Closed for lack of feedback from the author.

**Pull request closed without merging**
