### PR TITLE
fix crash when the source image is less than 3 pixels width/height

### PR DESCRIPTION
**Pull request by liulex**
If the last witdh or height of the last layer is less than `N`, it would create another layer with empty image and cause crash.

### CODE REVIEW

**Comment by axxel** [comment]
for that crash to happen you would need to call it with `threshold < 3`, right? That value would make absolutely no sens. The smallest meaningful value would be in the order of 100.

**Comment by liulex** [comment]
No, it's not the threshold, it's the `N`, which has a value of 3 and cannot be configured.

**Comment by liulex** [comment]
Suppose the threshold is 500, a 600x1 image would cause the crash without the fix.

**Comment by liulex** [comment]
Yes.

**Comment by axxel** [comment]
Thanks for the patch and the explanation.

**Pull request merged**
